# Generated by Django 3.1.2 on 2020-10-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DimCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'dim_category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCountry',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_country',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimCustomer',
            fields=[
                ('customer_id', models.TextField(primary_key=True, serialize=False)),
                ('customer_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_customer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimOrder',
            fields=[
                ('order_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_order',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimOrderdate',
            fields=[
                ('orderdate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hari', models.TextField()),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'dim_orderdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProduct',
            fields=[
                ('product_id', models.TextField(primary_key=True, serialize=False)),
                ('product_name', models.TextField()),
                ('product_type', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimRegion',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'dim_region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSegment',
            fields=[
                ('segment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('segment_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_segment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimShipment',
            fields=[
                ('shipment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('shipping_mode', models.TextField()),
            ],
            options={
                'db_table': 'dim_shipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimShippingdate',
            fields=[
                ('shippingdate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('hari', models.TextField()),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'dim_shippingdate',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimState',
            fields=[
                ('state_id', models.IntegerField(primary_key=True, serialize=False)),
                ('state_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_state',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSubcategory',
            fields=[
                ('subcategory_id', models.IntegerField(primary_key=True, serialize=False)),
                ('subcategory_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_subcategory',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactLogistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrived_quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_logistic',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FactSales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sales', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fact_sales',
                'managed': False,
            },
        ),
    ]
