# Generated by Django 3.1.2 on 2021-05-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_auto_20201104_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.BooleanField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.BooleanField()),
                ('is_active', models.BooleanField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimKategori',
            fields=[
                ('kategori_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_kategori', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'dim_kategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimKota',
            fields=[
                ('kota_id', models.AutoField(primary_key=True, serialize=False)),
                ('kota_name', models.TextField()),
            ],
            options={
                'db_table': 'dim_kota',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimModePengiriman',
            fields=[
                ('mode_pengiriman_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_mode_pengiriman', models.TextField()),
            ],
            options={
                'db_table': 'dim_mode_pengiriman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimNegara',
            fields=[
                ('negara_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_negara', models.TextField()),
            ],
            options={
                'db_table': 'dim_negara',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPelanggan',
            fields=[
                ('pelanggan_id', models.TextField(primary_key=True, serialize=False)),
                ('nama_pelanggan', models.TextField()),
            ],
            options={
                'db_table': 'dim_pelanggan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimPesanan',
            fields=[
                ('pesanan_id', models.TextField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'dim_pesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProduk',
            fields=[
                ('produk_id', models.TextField(primary_key=True, serialize=False)),
                ('nama_produk', models.TextField()),
                ('tipe_produk', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dim_produk',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimProvinsi',
            fields=[
                ('provinsi_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_provinsi', models.TextField()),
            ],
            options={
                'db_table': 'dim_provinsi',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSegmen',
            fields=[
                ('segmen_id', models.IntegerField(primary_key=True, serialize=False)),
                ('nama_segmen', models.TextField()),
            ],
            options={
                'db_table': 'dim_segmen',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimSubkategori',
            fields=[
                ('subkategori_id', models.AutoField(primary_key=True, serialize=False)),
                ('nama_subkategori', models.TextField()),
            ],
            options={
                'db_table': 'dim_subkategori',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTanggalPengiriman',
            fields=[
                ('tanggal_pengiriman_id', models.AutoField(primary_key=True, serialize=False)),
                ('hari', models.TextField()),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'dim_tanggal_pengiriman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DimTanggalPesanan',
            fields=[
                ('tanggal_pesanan_id', models.AutoField(primary_key=True, serialize=False)),
                ('hari', models.TextField()),
                ('tanggal', models.DateField()),
            ],
            options={
                'db_table': 'dim_tanggal_pesanan',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.SmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaktaPengiriman',
            fields=[
                ('nomer', models.AutoField(primary_key=True, serialize=False)),
                ('barang_diterima', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fakta_pengiriman',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FaktaPenjualan',
            fields=[
                ('nomer', models.AutoField(primary_key=True, serialize=False)),
                ('harga', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('profit', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('jumlah_barang', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'fakta_penjualan',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='DimCategory',
        ),
        migrations.DeleteModel(
            name='DimCity',
        ),
        migrations.DeleteModel(
            name='DimCountry',
        ),
        migrations.DeleteModel(
            name='DimCustomer',
        ),
        migrations.DeleteModel(
            name='DimOrder',
        ),
        migrations.DeleteModel(
            name='DimOrderdate',
        ),
        migrations.DeleteModel(
            name='DimProduct',
        ),
        migrations.DeleteModel(
            name='DimSegment',
        ),
        migrations.DeleteModel(
            name='DimShipment',
        ),
        migrations.DeleteModel(
            name='DimShippingdate',
        ),
        migrations.DeleteModel(
            name='DimState',
        ),
        migrations.DeleteModel(
            name='DimSubcategory',
        ),
        migrations.DeleteModel(
            name='FactLogistic',
        ),
        migrations.DeleteModel(
            name='FactSales',
        ),
    ]
